# Generated by Django 3.1 on 2020-08-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product',
            new_name='product_listing',
        ),
    ]
